# Generated by Django 3.0.6 on 2020-08-22 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.Category'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
